<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Fabienne Kraemer">
<meta name="author" content="Arjin Eser">
<meta name="author" content="Çağla Yıldız">
<meta name="dcterms.date" content="2024-11-14">

<title>Assessing Response Quality and Careless Responding in Multi-Item Scales</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="Resquin_Tutorial_v2_files/libs/clipboard/clipboard.min.js"></script>
<script src="Resquin_Tutorial_v2_files/libs/quarto-html/quarto.js"></script>
<script src="Resquin_Tutorial_v2_files/libs/quarto-html/popper.min.js"></script>
<script src="Resquin_Tutorial_v2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Resquin_Tutorial_v2_files/libs/quarto-html/anchor.min.js"></script>
<link href="Resquin_Tutorial_v2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Resquin_Tutorial_v2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Resquin_Tutorial_v2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Resquin_Tutorial_v2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Resquin_Tutorial_v2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#set-up" id="toc-set-up" class="nav-link" data-scroll-target="#set-up">Set-up</a>
  <ul class="collapse">
  <li><a href="#data-and-measurement-instruments" id="toc-data-and-measurement-instruments" class="nav-link" data-scroll-target="#data-and-measurement-instruments">Data and Measurement Instruments</a></li>
  <li><a href="#assessing-response-quality-and-response-quality-indicators" id="toc-assessing-response-quality-and-response-quality-indicators" class="nav-link" data-scroll-target="#assessing-response-quality-and-response-quality-indicators">Assessing Response Quality and Response Quality Indicators</a></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started">Getting started</a></li>
  <li><a href="#inspecting-data" id="toc-inspecting-data" class="nav-link" data-scroll-target="#inspecting-data">Inspecting data</a></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data preparation</a></li>
  </ul></li>
  <li><a href="#tool-application" id="toc-tool-application" class="nav-link" data-scroll-target="#tool-application">Tool application</a>
  <ul class="collapse">
  <li><a href="#calculating-indicators-of-response-distribution" id="toc-calculating-indicators-of-response-distribution" class="nav-link" data-scroll-target="#calculating-indicators-of-response-distribution">Calculating indicators of response distribution</a></li>
  <li><a href="#handling-respondents-with-missing-data" id="toc-handling-respondents-with-missing-data" class="nav-link" data-scroll-target="#handling-respondents-with-missing-data">Handling respondents with missing data</a></li>
  <li><a href="#indicators-of-response-distribution" id="toc-indicators-of-response-distribution" class="nav-link" data-scroll-target="#indicators-of-response-distribution">Indicators of response distribution</a></li>
  <li><a href="#calculating-indicators-of-various-response-styles" id="toc-calculating-indicators-of-various-response-styles" class="nav-link" data-scroll-target="#calculating-indicators-of-various-response-styles">Calculating indicators of various response styles</a></li>
  <li><a href="#indicators-of-response-styles" id="toc-indicators-of-response-styles" class="nav-link" data-scroll-target="#indicators-of-response-styles">Indicators of response styles</a></li>
  </ul></li>
  <li><a href="#conclusion-and-recommendations" id="toc-conclusion-and-recommendations" class="nav-link" data-scroll-target="#conclusion-and-recommendations">Conclusion and recommendations</a>
  <ul class="collapse">
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assessing Response Quality and Careless Responding in Multi-Item Scales</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Fabienne Kraemer </p>
             <p>Arjin Eser </p>
             <p>Çağla Yıldız </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 14, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<style>
/* Align text to justify for a consistent look */
p, h1, h2, h3, h4, h5, h6 {
  text-align: justify !important;
}
</style>
<section id="at-a-glance" class="level1">
<h1>At a glance</h1>
<p>What do we need to be aware of when analyzing responses of multi-item scales? Which response quality issues can affect data from multi-item scales? This tool gives an overview on the assessment of response quality in multi-item scales and guides you through the quality analysis with replicable R-code. Specifically, you will learn</p>
<ul>
<li><p>how to calculate and interpret different indicators of response distribution regarding potential data quality issues</p></li>
<li><p>how to calculate and interpret indicators of different response styles which can reflect poor response behavior</p></li>
<li><p>the caveats of certain response quality indicators and their suitability for different question types and response scales</p></li>
<li><p>what to do if you detect poor quality responses</p></li>
</ul>
<!--I added this as a side table of content in YAML as well, should we keep the below one as well?-->
<section id="table-of-content" class="level3">
<h3 class="anchored" data-anchor-id="table-of-content">Table of Content</h3>
<p><a href="#introduction">Introduction</a></p>
<p><a href="#set-up">Set-up</a></p>
<p><a href="#tool-application">Tool application</a></p>
<p><a href="#conclusion-and-recommendations">Conclusion and recommendations</a></p>
</section>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Psychological constructs, political or social attitudes as well as behavioral patterns are often measured by using multi-item scales in questionnaires. Multi-item scales comprise several items, questions, or statements that assess different aspects of the same underlying construct, i.e., gender-role attitudes or attitudes toward foreigners. Main concerns of multi-item scales usually revolve around the validity of the measurement instrument itself, i.e., do the several questions/items reflect the underlying construct or in other words: Does the scale really measure what it intends to measure? Established scales usually underwent a series of analyses and revisions to assess and ensure the validity and reliability of the measurement instrument. Nevertheless, collected data from these scales can still suffer from bias resulting from poor response behavior. Before analyzing data from these scales and drawing conclusions regarding a substantive research question, the quality of survey responses to these scales should be examined to avoid bias and ensure the validity of your results. In this tutorial, we will focus on the relationship between the concepts of political/institutional trust and environmental attitudes which both are measured by multi-item scales and assess the quality of given responses to these scales.</p>
</section>
<section id="set-up" class="level1">
<h1>Set-up</h1>
<section id="data-and-measurement-instruments" class="level2">
<h2 class="anchored" data-anchor-id="data-and-measurement-instruments">Data and Measurement Instruments</h2>
<p>For this tutorial, we use data from the GESIS Panel. The GESIS Panel is a German probability-based mixed-mode panel study which surveys respondents every three months on a variety of topics, such as political and social attitudes. We specifically use data from the 2nd and 3rd wave in 2014 from a sub-sample of the GESIS Panel (n=1,222). The data includes multi-item measurements of political trust and environmental attitudes.</p>
<!--side remark-->
<p>This sub-sample of the <span class="citation" data-cites="ZA5666">GESIS Panel (<a href="#ref-ZA5666" role="doc-biblioref">2017</a>)</span> is publicly accessible as the GESIS Panel Campus File. It contains a random 25% sample of the GESIS panel members surveyed in 2014 and comprises only a limited selection of variables from the originial GESIS Panel scientific use file. <!-----></p>
<p>Political trust is measured with a 10-item scale and a 7-point Likert response scale:</p>
<p><strong>Trust in Institutions:</strong> Trust in various political institutions.</p>
<p>How much do you personally trust the following public institutions or groups?</p>
<p><strong>Items:</strong></p>
<ul>
<li>bbzc078a: Trust in Bundestag</li>
<li>bbzc079a: Trust in federal government</li>
<li>bbzc080a: Trust in political parties</li>
<li>bbzc081a: Trust in judicial authorities</li>
<li>bbzc082a: Trust in police</li>
<li>bbzc083a: Trust in politicians</li>
<li>bbzc084a: Trust in media</li>
<li>bbzc085a: Trust in European Union</li>
<li>bbzc086a: Trust in United Nations</li>
<li>bbzc087a: Trust in Federal Constitutional Court</li>
</ul>
<p><strong>Response Scale:</strong> 1 = Don’t trust at all - 7 = Entirely trust</p>
<p>Environmental attitudes are measured with the established NEP (New Ecological Paradigm) scale by <span class="citation" data-cites="dunlap_et_al_2002">Dunlap et al. (<a href="#ref-dunlap_et_al_2002" role="doc-biblioref">2002</a>)</span> comprising 15 items on different aspects of environmental or climate attitudes. The multi-item scale uses a 5-point Likert response scale.</p>
<p><strong>NEP scale:</strong> Environmental attitudes</p>
<p>To what extent do you agree or disagree with the following statements?</p>
<p><strong>Items:</strong></p>
<ul>
<li>bczd005a: NEP-scale: Approaching maximum number of humans</li>
<li>bczd006a: NEP-scale: The right to adapt environment to the needs</li>
<li>bczd007a: NEP-scale: Consequences of human intervention</li>
<li>bczd008a: NEP-scale: Human ingenuity</li>
<li>bczd009a: NEP-scale: Abuse of the environment by humans</li>
<li>bczd010a: NEP-scale: Sufficient natural resources</li>
<li>bczd011a: NEP-scale: Equal rights for plants and animals</li>
<li>bczd012a: NEP-scale: Balance of nature stable enough</li>
<li>bczd013a: NEP-scale: Humans are subjected to natural laws</li>
<li>bczd014a: NEP-scale: Environmental crisis greatly exaggerated</li>
<li>bczd015a: NEP-scale: Earth is like spaceship</li>
<li>bczd016a: NEP-scale: Humans were assigned to rule over nature</li>
<li>bczd017a: NEP-scale: Balance of nature is very sensitive</li>
<li>bczd018a: NEP-scale: Control nature</li>
<li>bczd019a: NEP-scale: Environmental disaster</li>
</ul>
<p><strong>Response Scale:</strong> 1 = Fully agree; 2 = Agree; 3 = Neither nor; 4 = Don’t agree; 5 = Fully disagree</p>
</section>
<section id="assessing-response-quality-and-response-quality-indicators" class="level2">
<h2 class="anchored" data-anchor-id="assessing-response-quality-and-response-quality-indicators">Assessing Response Quality and Response Quality Indicators</h2>
<p>To ensure unbiased conclusions regarding a substantial relationship between two construct, we advise to initially investigate the quality of given responses to the respective measurement instruments. There are several indicators which can help identify low-quality responses and assess the response quality in multi-item scales.</p>
<p>In this tutorial, we will specifically look at several indicators of response distribution, such as:</p>
<ul>
<li>The proportion of missing responses across multiple items per respondent (<code>prop_na</code>)</li>
<li>The mean over multiple items per respondent (<code>ii_mean</code>)</li>
<li>The median over multiple items per respondent (<code>ii_median</code>)</li>
<li>The standard deviation across multiple items per respondent (<code>ii_sd</code>)</li>
<li>The <span data-bs-toggle="popover" data-bs-content="The Mahalanobis distance captures how different each respondent's pattern of answers is from the 'typical' response pattern of all respondents. A higher score indicates that the respondent’s answers are more unusual or inconsistent compared to the other respondents." style="text-decoration: underline; cursor: pointer;"> Mahalanobis distance</span> per respondent (<code>mahal</code>)</li>
</ul>
<script>
// Enable Bootstrap popovers on page load
document.addEventListener("DOMContentLoaded", function(){
  var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
  var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
    return new bootstrap.Popover(popoverTriggerEl, { trigger: "click" })
  })
});
</script>
<!-- I got this code from ChatGPT on how to code popovers in RMarkdown. Could you check if it works? Then we could implement it also for the other popover effects (if there are any). Thank you :-)-->
<p>Apart from peculiarities in the response distribution of our multi-item scales, we will further consider indicators of different response biases, namely:</p>
<style>
/* Hide link icons */
.accordion-header a {
  display: none;
}
</style>
<div id="termsAccordion" class="accordion">
<!-- Term 1 -->
<div class="accordion-item">
<h2 class="accordion-header anchored" id="headingOne">
<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
MRS: Middle response style
</button>
</h2>
<div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#termsAccordion">
<div class="accordion-body">
<pre><code>Tendency to select the neutral/middle option on a scale: The indicator captures the sum of mid-point responses across the items of the scale and is only valid if the scale has a numeric midpoint.</code></pre>
</div>
</div>
</div>
<!-- Term 2 -->
<div class="accordion-item">
<h2 class="accordion-header anchored" id="headingTwo">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
ARS: Acquiescence response style
</button>
</h2>
<div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#termsAccordion">
<div class="accordion-body">
<pre><code>Tendency to agree with statements irrespective of actual views. The indicator captures the sum of responses above the scale mid-point across the items of a scale and is only valid for scales with an agree-disagree format. </code></pre>
</div>
</div>
</div>
<!-- Term 3 -->
<div class="accordion-item">
<h2 class="accordion-header anchored" id="headingThree">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
ERS: Extreme response style
</button>
</h2>
<div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#termsAccordion">
<div class="accordion-body">
<pre><code>Tendency to select the lower or upper endpoint of a scale. The indicator captures the sum of scale endpoint responses across the items of a scale.</code></pre>
</div>
</div>
</div>
</div>
<!-- This is also code I got from ChatGPT on how to implement an accordeon for the list of response style indicators. Could you also check if this works? Thanks a lot!! -->
<p>To calculate these indicators for the assessment of response quality of our multi-item scales, we will use the <code>Resquin</code> package in R. The <code>resquin</code> package comprises different functions to calculate response quality indicators for multi-item scales. The quality indicators are calculated per respondent. Specifically, we will use the two functions <code>resp_distributions</code> (indicators of response distribution) and <code>resp_styles</code>(response style indicators), designed to assess response quality based on response distribution and on identifying certain response biases.</p>
</section>
<section id="getting-started" class="level2">
<h2 class="anchored" data-anchor-id="getting-started">Getting started</h2>
<p>To use <code>resquin</code>, we first need to install the package from the repository of CRAN, the Comprehensive R Archive Network. For installation, we can use the following commands:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Installing resquin</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"resquin"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading resquin into the R session</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(resquin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Alongside <code>resquin</code> itself, we will use other packages for setup, data preparation and analysis in this tutorial. To install and load these packages from CRAN simultaneously, we will use the <code>pacman</code> package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Installing pacman and loading pacman into the R session</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"pacman"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pacman)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Install and load other CRAN packages using pacman</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(devtools, pak, dplyr,ggplot2,tidyr,patchwork, knitr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After installation, we can import the survey data we want to analyze regarding its response quality. For both <code>resp_distributions</code> and <code>resp_styles</code> to calculate meaningful indicators, we need to import survey data in a wide format, i.e., with only one row per observation unit (respondent). For this tutorial, we import our data set directly from GitHub: <!--maybe let's rename the data for better usability --></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import data from github</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>raw_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"raw-data/ZA5666_v1-0-0.csv"</span>, <span class="at">header=</span><span class="cn">TRUE</span>, <span class="at">sep=</span><span class="st">";"</span>, <span class="at">na.strings=</span><span class="st">"NA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="inspecting-data" class="level2">
<h2 class="anchored" data-anchor-id="inspecting-data">Inspecting data</h2>
<p>Before delving into the analysis of response quality, let’s have a first look at the distribution of given responses to both multi-item scales:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating subset of political trust scale</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>start_col_trust <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">colnames</span>(raw_data) <span class="sc">==</span> <span class="st">"bbzc078a"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>end_col_trust <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">colnames</span>(raw_data) <span class="sc">==</span> <span class="st">"bbzc087a"</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>trust <span class="ot">&lt;-</span> raw_data[,start_col_trust<span class="sc">:</span>end_col_trust]</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating subset of NEP scale</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>start_col_NEP <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">colnames</span>(raw_data) <span class="sc">==</span> <span class="st">"bczd005a"</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>end_col_NEP <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">colnames</span>(raw_data) <span class="sc">==</span> <span class="st">"bczd019a"</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>NEP <span class="ot">&lt;-</span> raw_data[,start_col_NEP<span class="sc">:</span>end_col_NEP]</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspect responses to political trust scale</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>trust_responses <span class="ot">&lt;-</span> <span class="fu">lapply</span>(trust, <span class="cf">function</span>(x) <span class="fu">table</span>(x, <span class="at">useNA =</span> <span class="st">"ifany"</span>))</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the results</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>trust_responses</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$bbzc078a
x
-99 -77 -33 -22   1   2   3   4   5   6   7 
 22   2 170  10 105 109 192 290 201  92  29 

$bbzc079a
x
-99 -77 -33 -22   1   2   3   4   5   6   7 
 16   2 170  10 111 112 210 273 208  81  29 

$bbzc080a
x
-99 -77 -33 -22   1   2   3   4   5   6   7 
 31   2 170  10 126 208 260 271 111  24   9 

$bbzc081a
x
-111  -99  -77  -33  -22    1    2    3    4    5    6    7 
   2   24    2  170   10   42   68  117  208  269  221   89 

$bbzc082a
x
-99 -77 -33 -22   1   2   3   4   5   6   7 
 19   2 170  10  33  50  88 221 257 277  95 

$bbzc083a
x
-99 -77 -33 -22   1   2   3   4   5   6   7 
 25   2 170  10 176 242 258 229  89  16   5 

$bbzc084a
x
-99 -77 -33 -22   1   2   3   4   5   6   7 
 22   2 170  10 121 232 253 269  95  38  10 

$bbzc085a
x
-111  -99  -77  -33  -22    1    2    3    4    5    6    7 
   1   28    2  170   10  130  178  244  270  134   45   10 

$bbzc086a
x
-99 -77 -33 -22   1   2   3   4   5   6   7 
 29   2 170  10 109 162 212 273 162  72  21 

$bbzc087a
x
-99 -77 -33 -22   1   2   3   4   5   6   7 
 21   2 170  10  41  64 110 181 210 273 140 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspect responses to NEP </span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>NEP_responses <span class="ot">&lt;-</span> <span class="fu">lapply</span>(NEP, <span class="cf">function</span>(x) <span class="fu">table</span>(x, <span class="at">useNA =</span> <span class="st">"ifany"</span>))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the results</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>NEP_responses</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$bczd005a
x
-99 -77 -33 -22   1   2   3   4   5 
 14   4 195  15 139 403 233 198  21 

$bczd006a
x
-99 -77 -33 -22   1   2   3   4   5 
  8   4 195  15  36 208 205 453  98 

$bczd007a
x
-99 -77 -33 -22   1   2   3   4   5 
 11   4 195  15 349 529  68  43   8 

$bczd008a
x
-111  -99  -77  -33  -22    1    2    3    4    5 
   1   12    4  195   15   46  318  291  284   56 

$bczd009a
x
-99 -77 -33 -22   1   2   3   4   5 
 10   4 195  15 306 554  79  47  12 

$bczd010a
x
-99 -77 -33 -22   1   2   3   4   5 
 10   4 195  15 114 477 180 200  27 

$bczd011a
x
-99 -77 -33 -22   1   2   3   4   5 
 10   4 195  15 397 450  90  54   7 

$bczd012a
x
-99 -77 -33 -22   1   2   3   4   5 
  9   4 195  15   9  76 129 566 219 

$bczd013a
x
-99 -77 -33 -22   1   2   3   4   5 
  8   4 195  15 397 546  45   9   3 

$bczd014a
x
-99 -77 -33 -22   1   2   3   4   5 
  8   4 195  15  30 135 196 508 131 

$bczd015a
x
-99 -77 -33 -22   1   2   3   4   5 
 15   4 195  15 215 546 137  81  14 

$bczd016a
x
-111  -99  -77  -33  -22    1    2    3    4    5 
   1    9    4  195   15   16   98  168  440  276 

$bczd017a
x
-99 -77 -33 -22   1   2   3   4   5 
  7   4 195  15 318 544  78  54   7 

$bczd018a
x
-99 -77 -33 -22   1   2   3   4   5 
  7   4 195  15  16 153 267 455 110 

$bczd019a
x
-99 -77 -33 -22   1   2   3   4   5 
  9   4 195  15 241 504 164  82   8 </code></pre>
</div>
</div>
</section>
<section id="data-preparation" class="level2">
<h2 class="anchored" data-anchor-id="data-preparation">Data preparation</h2>
<p>A first overview of the response distribution of both scales shows that there are several missing values which are not defined as NA yet. For <code>resquin</code> to calculate meaningful indicators, we have to make sure that missings are coded to NA before we run any analyses:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get unique values for responses to political trust scale</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>unique_values_trust <span class="ot">&lt;-</span> <span class="fu">unique</span>(<span class="fu">unlist</span>(<span class="fu">lapply</span>(trust, unique)))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the unique values sorted in an ascending order</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(unique_values_trust)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] -111  -99  -77  -33  -22    1    2    3    4    5    6    7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Recode missing values to NA for responses to political trust scale</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>trust <span class="ot">&lt;-</span> trust <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">replace</span>(., . <span class="sc">%in%</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">22</span>, <span class="sc">-</span><span class="dv">33</span>, <span class="sc">-</span><span class="dv">77</span>, <span class="sc">-</span><span class="dv">99</span>, <span class="sc">-</span><span class="dv">111</span>), <span class="cn">NA</span>)))</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View the new recoded data frame</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(trust)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  bbzc078a bbzc079a bbzc080a bbzc081a bbzc082a bbzc083a bbzc084a bbzc085a
1        3        3        2        4        5        2        3        3
2       NA        6        3        5        5        3        4        4
3        5        6        3        6        6        3        4        4
4        1        1        1        5        4        1        2        1
5        3        3        3        4        4        3        3        3
6        4        4        4        4        4        4        4        4
  bbzc086a bbzc087a
1        3        5
2        3        6
3        4        6
4        1        5
5        3        3
6        4        4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get unique values for responses to NEP scale</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>unique_values_NEP <span class="ot">&lt;-</span> <span class="fu">unique</span>(<span class="fu">unlist</span>(<span class="fu">lapply</span>(NEP, unique)))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the unique values sorted in an ascending order</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(unique_values_NEP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] -111  -99  -77  -33  -22    1    2    3    4    5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Recode missing values to NA for responses to NEP scale</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>NEP <span class="ot">&lt;-</span> NEP <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">replace</span>(., . <span class="sc">%in%</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">22</span>, <span class="sc">-</span><span class="dv">33</span>, <span class="sc">-</span><span class="dv">77</span>, <span class="sc">-</span><span class="dv">99</span>, <span class="sc">-</span><span class="dv">111</span>), <span class="cn">NA</span>)))</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View the new recoded data frame</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(NEP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  bczd005a bczd006a bczd007a bczd008a bczd009a bczd010a bczd011a bczd012a
1        2        2        1        4        2        2        1        4
2        1        4        2        4        1        4        2        5
3        2        4        4        4        2        4        2        4
4        4        4        2        2        3        2        3        4
5        4        4        1        1        2        2        1        2
6       NA       NA       NA       NA       NA       NA       NA       NA
  bczd013a bczd014a bczd015a bczd016a bczd017a bczd018a bczd019a
1        2        4        2        4        1        3        2
2        1        4        2        4        2        4        2
3        2        4        4        4        2        2        2
4        2        4        2        3        2        3        3
5        1        4        4        4        2        4        3
6       NA       NA       NA       NA       NA       NA       NA</code></pre>
</div>
</div>
</section>
</section>
<section id="tool-application" class="level1">
<h1>Tool application</h1>
<section id="calculating-indicators-of-response-distribution" class="level2">
<h2 class="anchored" data-anchor-id="calculating-indicators-of-response-distribution">Calculating indicators of response distribution</h2>
<p>Now that we have prepared our data for analysis, we can proceed to the main analysis of response quality and calculate several response quality indicators using <code>resquin</code>. Let’s first look at the response distributions of both the institutional trust scale and the NEP scale in greater detail by using <code>resp_distributions</code>. We can use <code>resp_distributions</code> as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate indicators of response distribution with resp_distribution</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Institutional trust</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>trust_distribution <span class="ot">&lt;-</span> <span class="fu">resp_distributions</span>(trust)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results for the first 10 respondents</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>trust_distribution[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   n_na prop_na ii_mean    ii_sd ii_median    mahal
1     0     0.0     3.3 1.059350       3.0 1.291229
2     1     0.1      NA       NA        NA       NA
3     0     0.0     4.7 1.251666       4.5 2.722131
4     0     0.0     2.2 1.751190       1.0 2.963078
5     0     0.0     3.2 0.421637       3.0 1.400355
6     0     0.0     4.0 0.000000       4.0 1.534575
7     0     0.0     5.2 1.619328       5.0 3.799596
8     0     0.0     4.3 1.494434       3.5 2.828356
9     0     0.0     2.1 0.875595       2.0 2.387371
10    0     0.0     5.2 1.316561       5.0 3.295471</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Environmental attitudes </span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>NEP_distribution <span class="ot">&lt;-</span> <span class="fu">resp_distributions</span>(NEP)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>NEP_distribution[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   n_na prop_na  ii_mean     ii_sd ii_median    mahal
1     0       0 2.400000 1.1212238         2 3.150151
2     0       0 2.800000 1.3732131         2 3.062830
3     0       0 3.066667 1.0327956         4 5.015197
4     0       0 2.866667 0.8338094         3 3.146133
5     0       0 2.600000 1.2983506         2 5.232383
6    15       1       NA        NA        NA       NA
7     0       0 2.466667 1.3557637         2 2.928595
8     0       0 2.600000 1.5491933         2 5.230894
9     0       0 2.466667 1.4573296         2 3.406982
10    0       0 2.666667 1.7182494         2 5.830589</code></pre>
</div>
</div>
<p><code>resp_distributions</code> returns a data frame containing several indicators of response distribution per respondent (displayed as separate rows of the data frame). Inspecting the calculated indicators for the first 10 respondents in our data frame, we see that for 1 out of the first 10 respondents of the institutional trust scale and for 1 out of the first 10 respondents of the NEP scale no parameters of central tendency (i.e., ii_mean, ii_median) or variability (i.e., ii_sd, mahal) were calculated. The reason for this is that <code>resp_distributions</code> by default only calculates response distribution indicators for respondents who do not show any missing value in the analyzed multi-item scale. Accordingly, for all respondents who show a value higher than 0 for the indicator <code>n_na</code> (count of missing values), indicators of central tendency and variability are NA.</p>
<!-- Info Box with Title, No Background Color -->
<div style="border: 2px solid #007BFF; padding: 20px; border-radius: 8px;">
<p><strong>Package-specific feature</strong></p>
<p>
By specifying the option <code>min_valid_responses</code>, respondents with missing values in the multi-item scale can be included in the analysis of response quality. <code>min_valid_responses</code> takes on a numeric value between 0 and 1 and defines the share of valid responses a respondent must have to calculate the respective indicators of response distribution.
</p>
</div>
<!-- Here I got some code for creating a separate information box. Please also check if this works - thanks! :-) Then we can adapt it for the other info boxes we wanted to create -->
</section>
<section id="handling-respondents-with-missing-data" class="level2">
<h2 class="anchored" data-anchor-id="handling-respondents-with-missing-data">Handling respondents with missing data</h2>
<p>Generally, the more complete data we have from respondents on a multi-item scale, the better! Moreover, the majority of indicators is most meaningful when respondents show complete data across all items of a scale compared to calculating an indicator of response distribution for e.g., only two answered items. Usually, the absence of one value within a set of responses can already undermine the identification of response patterns. Nevertheless, by only including respondents with complete data, your sample can be drastically reduced and you might lose many observations with incomplete but “sufficient” data (e.g., respondents who responded to 4 out of 5 questions of a multi-item scale). To include respondents with incomplete data, you can simply decrease the necessary number of valid responses per respondent by specifying the <code>min_valid_responses</code> option. We advise to specify the cut-offs regarding how many valid answers a respondent should have depending on the number of items in your scale and to consider higher cut-offs or excluding respondents with NAs completely if the scale comprises only a few items, i.e., less than 10 items. Nevertheless, specifying cut-offs for valid responses is more or less arbitrary and should always be considered after looking at the data. In any case, make sure to thoroughly document and report which cut-off you used to exclude respondents from the analysis.</p>
<!-- Let's see if we can find any references from the literature on how to deal with NAs -->
<p>Due to a sufficient sample size, we will follow a strict approach and investigate response distribution indicators only for those respondents who show no missing values for the institutional trust and environmental attitudes scale.</p>
</section>
<section id="indicators-of-response-distribution" class="level2">
<h2 class="anchored" data-anchor-id="indicators-of-response-distribution">Indicators of response distribution</h2>
<p>To analyze the response distribution of institutional trust and environmental attitudes across <em>all respondents</em>, we calculate summary statistics and visualize their distribution for each indicator in the data frame generated by <code>resp_distributions</code>. This will help us understand typical response behaviors among the respondents as well as unusual response patterns overall.</p>
<section id="institutional-trust-scale" class="level3">
<h3 class="anchored" data-anchor-id="institutional-trust-scale">1. Institutional Trust Scale</h3>
<p>Let’s begin with the institutional trust scale:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize and print results over all respondents</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>trust_table <span class="ot">&lt;-</span> <span class="fu">summary</span>(trust_distribution)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(trust_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 3%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">n_na</th>
<th style="text-align: left;">prop_na</th>
<th style="text-align: left;">ii_mean</th>
<th style="text-align: left;">ii_sd</th>
<th style="text-align: left;">ii_median</th>
<th style="text-align: left;">mahal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Min. : 0.000</td>
<td style="text-align: left;">Min. :0.0000</td>
<td style="text-align: left;">Min. :1.000</td>
<td style="text-align: left;">Min. :0.0000</td>
<td style="text-align: left;">Min. :1.000</td>
<td style="text-align: left;">Min. :0.7761</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">1st Qu.: 0.000</td>
<td style="text-align: left;">1st Qu.:0.0000</td>
<td style="text-align: left;">1st Qu.:3.000</td>
<td style="text-align: left;">1st Qu.:0.8216</td>
<td style="text-align: left;">1st Qu.:3.000</td>
<td style="text-align: left;">1st Qu.:2.2210</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Median : 0.000</td>
<td style="text-align: left;">Median :0.0000</td>
<td style="text-align: left;">Median :3.800</td>
<td style="text-align: left;">Median :1.1353</td>
<td style="text-align: left;">Median :4.000</td>
<td style="text-align: left;">Median :2.7694</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Mean : 1.686</td>
<td style="text-align: left;">Mean :0.1686</td>
<td style="text-align: left;">Mean :3.755</td>
<td style="text-align: left;">Mean :1.1329</td>
<td style="text-align: left;">Mean :3.645</td>
<td style="text-align: left;">Mean :2.9646</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">3rd Qu.: 0.000</td>
<td style="text-align: left;">3rd Qu.:0.0000</td>
<td style="text-align: left;">3rd Qu.:4.500</td>
<td style="text-align: left;">3rd Qu.:1.4491</td>
<td style="text-align: left;">3rd Qu.:4.500</td>
<td style="text-align: left;">3rd Qu.:3.5130</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Max. :10.000</td>
<td style="text-align: left;">Max. :1.0000</td>
<td style="text-align: left;">Max. :7.000</td>
<td style="text-align: left;">Max. :3.1623</td>
<td style="text-align: left;">Max. :7.000</td>
<td style="text-align: left;">Max. :9.6995</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA’s :250</td>
<td style="text-align: left;">NA’s :250</td>
<td style="text-align: left;">NA’s :250</td>
<td style="text-align: left;">NA’s :250</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape the data for density and box plots</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>trust_distribution_long <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(trust_distribution, </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">cols =</span> <span class="fu">c</span>(<span class="st">"ii_mean"</span>, <span class="st">"ii_sd"</span>, <span class="st">"ii_median"</span>, <span class="st">"mahal"</span>), </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">names_to =</span> <span class="st">"Indicator"</span>, </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">values_to =</span> <span class="st">"Value"</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove NAs (for those we have no calculated indicators)</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>trust_distribution_long <span class="ot">&lt;-</span> trust_distribution_long <span class="sc">%&gt;%</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Value))</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean for each Indicator               </span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>mean_values <span class="ot">&lt;-</span> trust_distribution_long <span class="sc">%&gt;%</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Indicator) <span class="sc">%&gt;%</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_value =</span> <span class="fu">mean</span>(Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Create combined boxplot and density plot with a dashed line for each mean</span></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(trust_distribution_long, <span class="fu">aes</span>(<span class="at">x =</span> Value, <span class="at">y =</span> <span class="fu">after_stat</span>(scaled))) <span class="sc">+</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(scaled)), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="sc">-</span><span class="fl">0.5</span>), <span class="at">width =</span> <span class="fl">0.5</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightgray"</span>) <span class="sc">+</span></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">data =</span> mean_values, <span class="fu">aes</span>(<span class="at">xintercept =</span> mean_value, <span class="at">color =</span> <span class="st">"Mean"</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Mean"</span> <span class="ot">=</span> <span class="st">"black"</span>)) <span class="sc">+</span></span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Indicator, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Combined Density and Box Plots of Indicators with Mean Values"</span>,</span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Value"</span>,</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Scaled Density / Boxplot"</span>) <span class="sc">+</span></span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"right"</span>,</span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.title =</span> <span class="fu">element_blank</span>())  <span class="co"># Remove legend title</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Resquin_Tutorial_v2_files/figure-html/summary%20statistics%20trust-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The density and box plots provide a quick visualization of central tendency and variability parameters for each calculated indicator. Box plots highlight key summary statistics like the median, quartiles, and potential outliers, while density plots complement this by showing the distribution shape and peaks. Together, they give us a full picture of how response patterns across the items of the scales are distributed in our sample.</p>
<p>The <code>resp_distributions</code> function provides two measures of <strong>central tendency</strong>: <code>ii_mean</code> (average response) and <code>ii_median</code> (central response) for each respondent.</p>
<p>From our output on the distribution of both parameters <em>across all respondents</em> of the 10-item scale of institutional trust (ranging from 1 to 7), we can conclude the following:</p>
<ul>
<li>The mean of <code>ii_mean</code> is 3.76, and the median of <code>ii_mean</code> is 3.80. These parameters tell us that the average respondent selects a mean response of the value 3.8 across all items of the institutional trust scale. Looking at the median of <code>ii_mean</code>, we see that 50% of our respondents select a mean response up to the value of 4 across all items. The plot additionally indicates a nearly normal distribution of <code>ii_mean</code> with a slight skew towards lower values.</li>
<li>The <code>ii_median</code> has a mean value of 3.65 and a median value of 4.0. These parameters indicate that <em>on average</em> 50% of the given answers across the items of the institutional trust scale lie below the value of 3.7 and that half of the respondents give a value up to 4 for 50% of their responses across the items of the institutional trust scale.</li>
<li>Box plots for both indicators further undermine these parameters by showing that half of the respondents have scores between the values 3.0 and 4.5. Outliers exist at the value of 7, representing the highest possible value, while lower extremes are within a normal range.</li>
</ul>
<p><em>In summary</em>, the distributions of central tendency parameters show a concentration of responses around the value 4 which could indicate respondents’ tendency to select the mid-point or answers close to the mid-point of the scale avoiding giving extreme responses. Outliers among others are respondents who show a mean or median response across all items at the upper end of the response scale (“Entirely trust”). These respondents might need further checks to exclude the possibility of data quality issues.</p>
<p><code>resp_distributions</code> also provides two measures of <strong>variability</strong>: <code>ii_sd</code> (individual response variability) and <code>mahal</code> (deviation from overall response patterns). From the output on the distribution <em>across all respondent</em>, we can see the following:</p>
<ul>
<li><p>The mean <code>ii_sd</code> is 1.13, meaning, <em>on average</em>, respondents’ answers across the items of the scale vary by about 1 point from their average response across all items.</p></li>
<li><p>The third quartile of <code>ii_sd</code> is 1.45, meaning 75% of respondents have moderate variability in their responses, with some showing higher fluctuations around their personal mean response across items. According to the box plot, those respondents with a variability exceeding the value of 2.5 are outliers among the other respondents.</p></li>
<li><p>Mahalanobis distance (<code>mahal</code>) does not have a straightforward interpretation like <code>ii_sd</code>. However, respondents with <code>mahal</code> scores slightly above 5 exhibit highly dissimilar response patterns compared to the overall average response pattern across items. These outliers could indicate potential data quality concerns and it might be worthwhile to examine these respondents in more detail.</p></li>
</ul>
<p><em>In summary</em>, most respondents show moderate variability indicating consistent responding, which again might point towards a tendency to select non-extreme answers close to the mid-point of the scale. A few respondents show a somewhat high variability in their responses which could call for additional checks to assess whether their responses reflect poor response behavior. Mahalanobis distance can further hint at respondents whose patterns deviate substantially from the average response pattern across all respondents which might be a sign of poor response behavior.</p>
<p><strong>Straightlining or non-differentiation</strong></p>
<p>From the standard deviation across items we can additionally infer whether respondents show straightlining response behavior across the multiple items of each scale. <em>Straightlining or non-differentiation</em> describes the response pattern of selecting the identical answer to a series of questions or items of a scale. It can indicate whether a respondent properly processed the respective question(s) or used shortcuts to reduce cognitive burden which in turn produces poor quality answers that do not represent a respondents’ true values. To get a measure for straightlining response behavior, we generate a new indicator based on a respondents’ standard deviation across the several items:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generating straightlining indicator for institutional trust scale </span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>trust_distribution<span class="sc">$</span>non_diff <span class="ot">&lt;-</span> <span class="cn">NA</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>trust_distribution<span class="sc">$</span>non_diff[trust_distribution<span class="sc">$</span>ii_sd <span class="sc">==</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>trust_distribution<span class="sc">$</span>non_diff[trust_distribution<span class="sc">$</span>ii_sd <span class="sc">!=</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Get proportion of respondents who show straightlining response behavior</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>proportion_nondiff <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(trust_distribution<span class="sc">$</span>non_diff))[<span class="dv">2</span>]</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>proportion_nondiff</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1 
0.05144033 </code></pre>
</div>
</div>
<!-- Side remark -->
<p>Apart from a binary measure indicating the selection of the identical response option across items versus selecting at least two different response options across a set of items is only one of several possible operationalizations of straightlining or non-differentiation. For an overview of the different possible operationalizations used in research, see <span class="citation" data-cites="kim_et_al_2019">Kim et al. (<a href="#ref-kim_et_al_2019" role="doc-biblioref">2019</a>)</span>. <!-- REFERENCE ADDED: Kim, Y., Dykema, J., Stevenson, J., Black, P., & Moberg, D. P. (2019). Straightlining: Overview of measurement, comparison of indicators, and effects in mail–web mixed-mode surveys. Social Science Computer Review, 37(2), 214-233. --></p>
<p>The results show that about 5% of respondents show <strong>straightlining response behavior</strong> in the institutional trust scale, meaning that 5% of respondents selected the identical answer across the several items. This is a relatively low proportion of straightlining behavior across respondents and does not indicate general data quality issues. However, it is necessary to flag these respondents who show straightlining across the items of a scale for a further investigation of their response behavior. The code below creates a new variable in the dataset, flagging respondents with zero variation in their responses as <code>TRUE</code>; otherwise, it flags them as <code>FALSE</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Flag respondents with zero variation in responses (ii_sd == 0)</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>trust_distribution<span class="sc">$</span>straightlining_flag <span class="ot">&lt;-</span> trust_distribution<span class="sc">$</span>ii_sd <span class="sc">==</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<!--Info box -->
<p><strong>Be careful!</strong></p>
<p>Whereas straightlining can indicate “careless” response behavior resulting in poor quality responses, we advise to always pay attention to the contents of the several items of a scale before drawing conclusions. For some multi-item scales, selecting identical answers across all the items can be plausible and reflect respondents’ true values. On the other hand, some scales comprise reversely coded items, meaning that selecting the identical answer for such items is contradictory regarding the surveyed attitude or behavior. In this case straightlining might be more likely implausible and might more likely represent poor quality responses. In this case, however, all items are identically polarized and cover trust in several official institutions. Showing the identical answer across all items might reflect genuine distrust or trust in institutions overall. To make sure that you are in fact identifying careless respondents, we advise to look at respondents’ response times for the question at hand. Identifying extremely low response times against this background is a common strategy to approach the question of whether respondents did not pay attention to the question or show genuine undifferentiated answers.</p>
</section>
<section id="nep-scale" class="level3">
<h3 class="anchored" data-anchor-id="nep-scale">2. NEP Scale</h3>
<p>Now let’s move on to inspecting the central tendency and variability parameters for the NEP scale:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize and print results over all respondents</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>NEP_table <span class="ot">&lt;-</span> <span class="fu">summary</span>(NEP_distribution)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(NEP_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 3%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">n_na</th>
<th style="text-align: left;">prop_na</th>
<th style="text-align: left;">ii_mean</th>
<th style="text-align: left;">ii_sd</th>
<th style="text-align: left;">ii_median</th>
<th style="text-align: left;">mahal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Min. : 0.000</td>
<td style="text-align: left;">Min. :0.0000</td>
<td style="text-align: left;">Min. :1.000</td>
<td style="text-align: left;">Min. :0.0000</td>
<td style="text-align: left;">Min. :1.000</td>
<td style="text-align: left;">Min. :1.517</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">1st Qu.: 0.000</td>
<td style="text-align: left;">1st Qu.:0.0000</td>
<td style="text-align: left;">1st Qu.:2.467</td>
<td style="text-align: left;">1st Qu.:0.9155</td>
<td style="text-align: left;">1st Qu.:2.000</td>
<td style="text-align: left;">1st Qu.:2.914</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Median : 0.000</td>
<td style="text-align: left;">Median :0.0000</td>
<td style="text-align: left;">Median :2.667</td>
<td style="text-align: left;">Median :1.1212</td>
<td style="text-align: left;">Median :2.000</td>
<td style="text-align: left;">Median :3.540</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Mean : 2.749</td>
<td style="text-align: left;">Mean :0.1833</td>
<td style="text-align: left;">Mean :2.639</td>
<td style="text-align: left;">Mean :1.1516</td>
<td style="text-align: left;">Mean :2.335</td>
<td style="text-align: left;">Mean :3.710</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">3rd Qu.: 0.000</td>
<td style="text-align: left;">3rd Qu.:0.0000</td>
<td style="text-align: left;">3rd Qu.:2.867</td>
<td style="text-align: left;">3rd Qu.:1.3870</td>
<td style="text-align: left;">3rd Qu.:3.000</td>
<td style="text-align: left;">3rd Qu.:4.334</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Max. :15.000</td>
<td style="text-align: left;">Max. :1.0000</td>
<td style="text-align: left;">Max. :3.733</td>
<td style="text-align: left;">Max. :2.0656</td>
<td style="text-align: left;">Max. :5.000</td>
<td style="text-align: left;">Max. :8.170</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA’s :285</td>
<td style="text-align: left;">NA’s :285</td>
<td style="text-align: left;">NA’s :285</td>
<td style="text-align: left;">NA’s :285</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape the data for density and box plots</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>NEP_distribution_long <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(NEP_distribution, </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">cols =</span> <span class="fu">c</span>(<span class="st">"ii_mean"</span>, <span class="st">"ii_sd"</span>, <span class="st">"ii_median"</span>, <span class="st">"mahal"</span>), </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">names_to =</span> <span class="st">"Indicator"</span>, </span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">values_to =</span> <span class="st">"Value"</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove non-finite values</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>NEP_distribution_long <span class="ot">&lt;-</span> NEP_distribution_long <span class="sc">%&gt;%</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Value) <span class="sc">&amp;</span> <span class="fu">is.finite</span>(Value))</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean for each Indicator</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>mean_values <span class="ot">&lt;-</span> NEP_distribution_long <span class="sc">%&gt;%</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Indicator) <span class="sc">%&gt;%</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_value =</span> <span class="fu">mean</span>(Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Create combined boxplot and density plot with a dashed line for each mean</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(NEP_distribution_long, <span class="fu">aes</span>(<span class="at">x =</span> Value, <span class="at">y =</span> <span class="fu">after_stat</span>(scaled))) <span class="sc">+</span></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(scaled)), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="sc">-</span><span class="fl">0.5</span>), <span class="at">width =</span> <span class="fl">0.5</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightgray"</span>) <span class="sc">+</span></span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">data =</span> mean_values, <span class="fu">aes</span>(<span class="at">xintercept =</span> mean_value, <span class="at">color =</span> <span class="st">"Mean"</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Mean"</span> <span class="ot">=</span> <span class="st">"black"</span>)) <span class="sc">+</span></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Indicator, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Combined Density and Box Plots of Indicators with Mean Values"</span>,</span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Value"</span>,</span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Scaled Density / Boxplot"</span>) <span class="sc">+</span></span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"right"</span>,</span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.title =</span> <span class="fu">element_blank</span>()) <span class="co"># Remove legend title</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Resquin_Tutorial_v2_files/figure-html/summary%20statistics%20NEP-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Again, the output shows the distribution of the central tendency parameters <em>across all respondents</em>. For the 15-item NEP scale (ranging from 1 to 5), our <strong>central tendency measures</strong> show the following:</p>
<ul>
<li>The mean of <code>ii_mean</code> is 2.64, and the median of <code>ii_mean</code> is 2.67. According to these parameters, the <em>average respondent</em> shows a personal mean response of 2.6 across all items of the scale whereas half of the respondents give a mean response across all items up to the value of 2.7. The plots show an almost normal distribution centered around the mid-point of the scale. Respondents with mean responses at the lower end (agree) and upper end (disagree) of the scale are outliers among the other respondents in the sample.</li>
<li>The <code>ii_median</code> has a mean value of 2.34 and a median value of 2.0. These parameters suggest that <em>on average</em> 50% of given answers to the items of the scale lie below the value of 2.3 and that for half of the respondents 50% of their answers to the items of the NEP scale lie below the value of 2. The plots further undermine this by showing a noticeable concentration of responses at the values 2 and 3. Respondents with a median response of “fully disagree” are outliers among the other respondents.</li>
</ul>
<p><em>In summary</em>, the distributions of the calculated central tendency indicators again show clustering of responses around the values 2 and 3 with 3 representing the scale mid-point. This clear concentration around the mid-points of the scale could again indicate respondents’ tendency to select scale mid-points rather than extreme answers. Respondents with mean extreme responses of both full agreement or full disagreement are outliers in the sample and might need additional checks to exclude data quality issues.</p>
<p>From the output of the distribution of <strong>variability measures</strong> across all respondents, we can conclude:</p>
<ul>
<li><p>The mean <code>ii_sd</code> is 1.15, which indicates that, <em>on average</em>, responses across all items vary by about 1 point from their individual mean response across items. While somewhat higher fluctuations up to 2 are within the normal range among the sample, no fluctuation at all (<code>ii_sd</code> = 0), meaning that respondents select the identical answer for every item is an outlier.</p></li>
<li><p>The plot displaying the distribution of the Mahalanobis distance (<code>mahal</code>) across all respondents shows that respondents with a <code>mahal</code> score near or above 6 are outliers in the sample with atypical responses, compared to the average responding pattern of the other respondents.</p></li>
</ul>
<p><em>In summary</em>, most respondents show some variability across the items of the scale, however, a few respondents show no variability at all meaning they provide identical answers across all items and are outliers compared to the rest of the sample. These respondents along with respondents who are extremely dissimilar from the average response pattern (indicated by the <code>mahal</code> indicator) should be further investigated as they could exhibit poor response behavior. We especially assume a data quality concern regarding respondents who show zero variability in responses, that is show straightlining.</p>
<p><strong>Straightlining or non-differentiation</strong></p>
<p>Unlike the institutional trust scale, the NEP scale comprises several reversely coded items (i.e., meaning that some of the items are positively formulated while others are negatively worded with respect to environmental attitudes). To better understand the difference, we have to look at the item contents again:</p>
<p><strong>Question:</strong> To what extent do you agree or disagree with the following statements?</p>
<p><strong>Response Scale:</strong> 1 = Fully agree; 2 = Agree; 3 = Neither nor; 4 = Don’t agree; 5 = Fully disagree</p>
<p><strong>Items:</strong></p>
<ol type="1">
<li>We are approaching the limit of the number of people the earth can support <u>(<em>Pro-environmental)</em></u></li>
<li>Humans have the right to modify the natural environment to suit their needs <u><em>(Anti-environmental)</em></u></li>
<li>When humans interfere with nature it often produces disastrous consequences <u>(<em>Pro-environmental)</em></u></li>
<li>Human ingenuity will ensure that we do NOT make the earth unlivable <u><em>(Anti-environmental)</em></u></li>
<li>Humans are severely abusing the environment <u>(<em>Pro-environmental)</em></u></li>
<li>There are enough resources on the planet - we just have to learn how to use them <u><em>(Anti-environmental)</em></u></li>
<li>Plants and animals have as much right as humans to exist <u>(<em>Pro-environmental)</em></u></li>
<li>The balance of nature is strong enough to cope with the impacts of modern industrial nations <u><em>(Anti-environmental)</em></u></li>
<li>Despite our special abilities humans are still subject to the laws of nature <u>(<em>Pro-environmental)</em></u></li>
<li>The so called ‘ecological crisis’ facing humankind has been greatly exaggerated <u><em>(Anti-environmental)</em></u></li>
<li>The earth is like a spaceship with very limited room and resources <u>(<em>Pro-environmental)</em></u></li>
<li>Humans were meant to rule over the rest of nature <u><em>(Anti-environmental)</em></u></li>
<li>The balance of nature is very delicate and easily upset <u>(<em>Pro-environmental)</em></u></li>
<li>Humans will eventually learn enough about how nature works to be able to control it <u><em>(Anti-environmental)</em></u></li>
<li>If things continue on their present course, we will soon experience a major ecological catastrophe <u>(<em>Pro-environmental)</em></u></li>
</ol>
<p>8 of the items are “positively” worded, with a response of 1 indicating a pro-environmental attitude. In contrast, the remaining 7 items are “negatively” worded, where a response of 1 indicates an anti-environmental attitude. As a result, respondents showing straightlining (i.e., giving the identical response to all items) contradict attitudinal aspects of previous items, suggesting respondents indeed show <strong>careless responding</strong>. This is especially true if respondents select identical responses at the extremes of the scale. However, we have to again be careful with hasty conclusions: In the case of respondents straightlining across the mid-point of the scale, we cannot immediately rule out the possibility of genuine ambiguity and should perform further checks to examine the possibility of poor quality responses. Nevertheless, straightlining in the NEP scale might especially pose a threat for data quality and should be investigated:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generating straightlining indicator for institutional trust scale </span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>NEP_distribution<span class="sc">$</span>non_diff <span class="ot">&lt;-</span> <span class="cn">NA</span> </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>NEP_distribution<span class="sc">$</span>non_diff[NEP_distribution<span class="sc">$</span>ii_sd <span class="sc">==</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>NEP_distribution<span class="sc">$</span>non_diff[NEP_distribution<span class="sc">$</span>ii_sd <span class="sc">!=</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Get proportion of respondents who show straightlining response behavior</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>proportion_nondiff <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(NEP_distribution<span class="sc">$</span>non_diff))[<span class="dv">2</span>]</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>proportion_nondiff</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          1 
0.005336179 </code></pre>
</div>
</div>
<p>For the NEP scale, we can see that 0.5% of respondents show straightlining across the several items of the scale. Despite the low prevalence of straightlining in the data, respondents who straightlined in the NEP scale are highly likely to show poor quality responses and should be flagged for further analyses. Below code flags respondents who show zero variation in their responses with a new variable named <code>straightlining_flag</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Flag respondents with zero variation in responses (ii_sd == 0)</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>NEP_distribution<span class="sc">$</span>straightlining_flag <span class="ot">&lt;-</span> NEP_distribution<span class="sc">$</span>ii_sd <span class="sc">==</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<!--Info box start-->
<p><strong>Be careful!</strong></p>
<p>As the NEP scale includes items with both positive and negative wordings, the response distribution indicators cannot be directly used for the description of the distribution of pro- or anti-environmental attitudes. To derive substantively meaningful conclusions from the indicators (e.g., average environmental attitudes among the respondents), it’s necessary to reverse-code either the positively or negatively worded items. This ensures that all items reflect the same directional attitude. For the recoding, you can use the following code chunk:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new data frame by copying the original NEP data</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>NEP_recoded <span class="ot">&lt;-</span> NEP</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Reverse code the negatively worded items in the new data frame</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>NEP_recoded<span class="sc">$</span>bczd006a <span class="ot">&lt;-</span> <span class="dv">6</span> <span class="sc">-</span> NEP_recoded<span class="sc">$</span>bczd006a  <span class="co"># Q2: Humans have the right to modify the natural environment</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>NEP_recoded<span class="sc">$</span>bczd008a <span class="ot">&lt;-</span> <span class="dv">6</span> <span class="sc">-</span> NEP_recoded<span class="sc">$</span>bczd008a  <span class="co"># Q4: Human ingenuity</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>NEP_recoded<span class="sc">$</span>bczd010a <span class="ot">&lt;-</span> <span class="dv">6</span> <span class="sc">-</span> NEP_recoded<span class="sc">$</span>bczd010a  <span class="co"># Q6: There are enough resources</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>NEP_recoded<span class="sc">$</span>bczd012a <span class="ot">&lt;-</span> <span class="dv">6</span> <span class="sc">-</span> NEP_recoded<span class="sc">$</span>bczd012a  <span class="co"># Q8: The balance of nature is strong enough</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>NEP_recoded<span class="sc">$</span>bczd014a <span class="ot">&lt;-</span> <span class="dv">6</span> <span class="sc">-</span> NEP_recoded<span class="sc">$</span>bczd014a  <span class="co"># Q10: Ecological crisis exaggerated</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>NEP_recoded<span class="sc">$</span>bczd016a <span class="ot">&lt;-</span> <span class="dv">6</span> <span class="sc">-</span> NEP_recoded<span class="sc">$</span>bczd016a  <span class="co"># Q12: Humans were meant to rule over nature</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>NEP_recoded<span class="sc">$</span>bczd018a <span class="ot">&lt;-</span> <span class="dv">6</span> <span class="sc">-</span> NEP_recoded<span class="sc">$</span>bczd018a  <span class="co"># Q14: Control nature</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="calculating-indicators-of-various-response-styles" class="level2">
<h2 class="anchored" data-anchor-id="calculating-indicators-of-various-response-styles">Calculating indicators of various response styles</h2>
<p>After investigating the response distribution of both the institutional trust scale and the NEP scale, let’s now take a closer look on systematic response styles that can indicate poor quality responses in multi-item scales. For this, we use the <code>resp_styles</code> function of the <code>resquin</code> package, which calculates indicators for the following response styles:</p>
<p><strong>Response Styles:</strong></p>
<ul>
<li><p><strong>Mid-point response style (MRS):</strong> Tendency to choose the mid-point of a response scale</p></li>
<li><p><strong>Acquiescence (ARS):</strong> Tendency to agree with statements</p></li>
<li><p><strong>Extreme Response Style (ERS):</strong> Tendency to select the endpoints of a response scale</p></li>
</ul>
<p>To use <code>resp_styles</code>, we first need to specify the range of the response scale of the underlying multi-item scale or matrix question. Only with information on the range, and therefore on the existence of a mid-point and the endpoints of the response scale, <code>resp_styles</code> can calculate indicators for the different response styles. Similar to <code>resp_distributions</code>, we can additionally specify the proportion of valid responses respondents should have on the multi-item scale (<code>min_valid_responses</code>) to calculate response style indicators. To enable the calculation of all response style indicators per respondent, we only include those respondents who show no NAs across items. We can further determine whether we want <code>resp_styles</code> to simply return the counts of each response style across items or if it should return the proportion of a specific response behavior out of all the items a respondent has answered. Although the proportion of a certain response behavior is generally more informative than the mere count, we specify the option <code>normalize = FALSE</code> for our analysis in this tutorial.</p>
<!-- I have noticed the we had an error in the below NEP calculation, scale was 7 in the previous files and I have changed it to 5 here -->
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating response style indicators for institutional trust</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>trust_respstyles <span class="ot">&lt;-</span> <span class="fu">resp_styles</span>(trust, <span class="dv">1</span>, <span class="dv">7</span>, <span class="at">min_valid_responses =</span> <span class="dv">1</span>, <span class="at">normalize =</span> <span class="cn">FALSE</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results of the first 10 respondents</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>trust_respstyles[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   MRS ARS DRS ERS NERS
1    1   2   7   0   10
2   NA  NA  NA  NA   NA
3    3   5   2   0   10
4    1   2   7   6    4
5    2   0   8   0   10
6   10   0   0   0   10
7    2   7   1   3    7
8    1   4   5   0   10
9    0   0  10   3    7
10   2   7   1   2    8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating response style indicators for environmental attitudes</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>NEP_respstyles <span class="ot">&lt;-</span> <span class="fu">resp_styles</span>(NEP, <span class="dv">1</span>, <span class="dv">5</span>, <span class="at">min_valid_responses =</span> <span class="dv">1</span>, <span class="at">normalize =</span> <span class="cn">FALSE</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results of the first 10 respondents</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>NEP_respstyles[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   MRS ARS DRS ERS NERS
1    1   4  10   3   12
2    0   7   8   4   11
3    0   8   7   0   15
4    5   4   6   0   15
5    1   6   8   4   11
6   NA  NA  NA  NA   NA
7    0   6   9   5   10
8    3   4   8   8    7
9    2   4   9   7    8
10   2   5   8  10    5</code></pre>
</div>
</div>
<p>As with <code>resp_distributions</code>, <code>resp_styles</code> returns a data frame containing the several response style indicators per respondent (displayed as separate rows of the data frame). Again, let’s first inspect the calculated indicators for the first 10 respondents in our data frame: Similar to <code>resp_distributions</code> we see that for 1 out of the first 10 respondents of the institutional trust scale and for 1 out of the first 10 respondents of the NEP scale, no indicators were calculated due to our specification of <code>min_valid_responses</code>, which only included respondents without NA across items into the analysis.</p>
</section>
<section id="indicators-of-response-styles" class="level2">
<h2 class="anchored" data-anchor-id="indicators-of-response-styles">Indicators of response styles</h2>
<p>To make statements about the occurrence of the specific response styles in the institutional trust and NEP scale across <em>all respondents</em>, we have to again calculate and visualize summary statistics for each indicator in the data frame produced by <code>resp_styles</code>.</p>
<section id="institutional-trust-scale-1" class="level3">
<h3 class="anchored" data-anchor-id="institutional-trust-scale-1">1. Institutional Trust Scale</h3>
<p>Let’s again begin with the institutional trust scale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize and print results over all respondents</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>trust_respstyles_table <span class="ot">&lt;-</span> <span class="fu">summary</span>(trust_respstyles)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(trust_respstyles_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 3%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">MRS</th>
<th style="text-align: left;">ARS</th>
<th style="text-align: left;">DRS</th>
<th style="text-align: left;">ERS</th>
<th style="text-align: left;">NERS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Min. : 0.000</td>
<td style="text-align: left;">Min. : 0.000</td>
<td style="text-align: left;">Min. : 0.000</td>
<td style="text-align: left;">Min. : 0.000</td>
<td style="text-align: left;">Min. : 0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">1st Qu.: 1.000</td>
<td style="text-align: left;">1st Qu.: 1.000</td>
<td style="text-align: left;">1st Qu.: 1.000</td>
<td style="text-align: left;">1st Qu.: 0.000</td>
<td style="text-align: left;">1st Qu.: 8.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Median : 2.000</td>
<td style="text-align: left;">Median : 3.000</td>
<td style="text-align: left;">Median : 4.000</td>
<td style="text-align: left;">Median : 0.000</td>
<td style="text-align: left;">Median :10.000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Mean : 2.443</td>
<td style="text-align: left;">Mean : 3.254</td>
<td style="text-align: left;">Mean : 4.302</td>
<td style="text-align: left;">Mean : 1.392</td>
<td style="text-align: left;">Mean : 8.608</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">3rd Qu.: 4.000</td>
<td style="text-align: left;">3rd Qu.: 5.000</td>
<td style="text-align: left;">3rd Qu.: 7.000</td>
<td style="text-align: left;">3rd Qu.: 2.000</td>
<td style="text-align: left;">3rd Qu.:10.000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Max. :10.000</td>
<td style="text-align: left;">Max. :10.000</td>
<td style="text-align: left;">Max. :10.000</td>
<td style="text-align: left;">Max. :10.000</td>
<td style="text-align: left;">Max. :10.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">NA’s :250</td>
<td style="text-align: left;">NA’s :250</td>
<td style="text-align: left;">NA’s :250</td>
<td style="text-align: left;">NA’s :250</td>
<td style="text-align: left;">NA’s :250</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape the data for density and box plots</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>trust__respstyles_long <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(trust_respstyles, </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">cols =</span> <span class="fu">c</span>(<span class="st">"MRS"</span>, <span class="st">"ARS"</span>, <span class="st">"ERS"</span>), </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">names_to =</span> <span class="st">"Indicator"</span>, </span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">values_to =</span> <span class="st">"Value"</span>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove NAs (for those we have no calculated indicators)</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>trust__respstyles_long <span class="ot">&lt;-</span> trust__respstyles_long <span class="sc">%&gt;%</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Value))</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean for each Indicator</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>mean_values <span class="ot">&lt;-</span> trust__respstyles_long <span class="sc">%&gt;%</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Indicator) <span class="sc">%&gt;%</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_value =</span> <span class="fu">mean</span>(Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Create combined boxplot and density plot with a dashed line for each mean</span></span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(trust__respstyles_long, <span class="fu">aes</span>(<span class="at">x =</span> Value, <span class="at">y =</span> <span class="fu">after_stat</span>(scaled))) <span class="sc">+</span></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(scaled)), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="sc">-</span><span class="fl">0.5</span>), <span class="at">width =</span> <span class="fl">0.5</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightgray"</span>) <span class="sc">+</span></span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">data =</span> mean_values, <span class="fu">aes</span>(<span class="at">xintercept =</span> mean_value, <span class="at">color =</span> <span class="st">"Mean"</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Mean"</span> <span class="ot">=</span> <span class="st">"black"</span>)) <span class="sc">+</span></span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Indicator, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Combined Density and Box Plots of Indicators with Mean Values"</span>,</span>
<span id="cb39-25"><a href="#cb39-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Value"</span>,</span>
<span id="cb39-26"><a href="#cb39-26" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Scaled Density / Boxplot"</span>) <span class="sc">+</span></span>
<span id="cb39-27"><a href="#cb39-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb39-28"><a href="#cb39-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"right"</span>,</span>
<span id="cb39-29"><a href="#cb39-29" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.title =</span> <span class="fu">element_blank</span>())  <span class="co"># Remove legend title</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Resquin_Tutorial_v2_files/figure-html/summary%20statistics%20trust%20resp_styles-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<!-- I have reduced the plots to include only MRS, ARS and ERS -->
<p>Looking at the response style indicators across all respondents of the institutional trust scale, we see the following patterns:</p>
<ul>
<li><p><strong><em>MRS:</em></strong> On average, respondents in our sample tend to select the midpoint of the scale (response of the value 4) for about two out of ten items. The boxplot shows that selecting anywhere between 0 to 8 midpoint responses across the items of the scale lies within the normal range among the sample. However, respondents who select the scale mid-point for 9 or 10 items are outliers, reflecting an usual high amount of given mid-point answers in the sample.</p></li>
<li><p><strong><em>ARS:</em></strong> On average, respondents “agree” with about three out of ten items. The ARS indicator defines agreement as selecting response options above the scale mid-point, that is every response that indicates some level of trust toward a specific institutions or in other words, “agrees” with the trustworthiness of that institution. While 75% of respondents do not agree with more than five out of the ten items, agreement up to every item of the scale falls within the typical distribution range of the sample and does so far not raise any concerns for the response quality of the institutional trust scale.</p></li>
<li><p><strong><em>ERS:</em></strong> On average, respondents select extreme responses (i.e., the lower and upper endpoint of the scale) for only one out of ten items. Moreover, the majority of respondents does not provide more than two extreme responses across the items of the scale. Respondents providing more than five extreme responses are outliers in the sample, indicating a potential bias of those responses.</p></li>
</ul>
<p><strong><em>In summary</em></strong>, the investigated response style indicators reveal that the majority of respondents does not show an excessive use of the mid-point as well as the endpoints of the institutional trust scale. Respondents who (almost) consistently select middle responses (which could also indicate straightlining behavior) and respondents with more than five extreme responses across items are outliers. These respondents should be further checked for anomalies in their response behavior (e.g., their response times) to exclude data quality concerns.</p>
<!--Info box -->
<p><strong>Be careful!</strong> When interpreting the indicator of acquiescence response style (ARS), be aware that strictly speaking you can only meaningfully interpret the indicator for actual agreement/disagreement - scales. For the purpose of this tutorial, we calculated and interpreted it for the trust scale ranging from complete distrust to complete trust to show how to extract some information about potential data quality issues from it. However, for scientific publications or data quality reports, we recommend to not use the ARS-indicator for scales other than agreement/disagreement - scales. Be also aware that the calculation of the ARS indicator assumes that the response scale is positively polarized, i.e., higher values of the response scale reflect higher levels of agreement with certain statements or issues.</p>
<!--Info box -->
<p><strong>Package-specific feature</strong> Apart from MRS, ARS, and ERS, the <code>resquin</code>-package additionally calculates an indicator for disacquiescence response style (DRS), i.e., the tendency to disagree with statements, and an indicator for non-extreme response style (NERS), i.e., the tendency to select non- extreme answers across a set of items. When interpreting the indicators for these response styles, keep in mind that the DRS-indicator is the <em>direct opposite</em> of the ARS-indicator and the NERS-indicator is the <em>direct inverse</em> of the ERS-indicator. Especially, for NERS and ERS it might be pointless to meaningfully interpret both indicators at the same time.</p>
</section>
<section id="nep-scale-1" class="level3">
<h3 class="anchored" data-anchor-id="nep-scale-1">2. NEP Scale</h3>
<!-- I have positively coded the scale and add a brief explanation. We may add this as Be Careful! box maybe-->
<p><strong>Be careful!</strong> Remember that ARS reflects the tendency to agree with statements and therefore assumes a positively polarized scale, where higher values indicate stronger agreement. However, the NEP scale is negatively polarized, with lower values indicating agreement (1 = fully agree). To compute ARS accurately, we need to reverse-code all the items so that <code>5</code> indicates agreement and <code>1</code> indicates disagreement. After this transformation, we should then recalculate the response style indicators on the reverse-coded data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the columns to reverse-code</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>NEP_columns <span class="ot">&lt;-</span> <span class="fu">colnames</span>(NEP)  <span class="co"># Replace with specific columns if needed</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a reversed version of NEP data and perform reverse-coding to positively polarize the scale</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>NEP_positively_polarized <span class="ot">&lt;-</span> NEP</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>NEP_positively_polarized[NEP_columns] <span class="ot">&lt;-</span> <span class="dv">6</span> <span class="sc">-</span> NEP[NEP_columns]</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate response style indicators on the positively polarized NEP data</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>NEP_positively_polarized_respstyles <span class="ot">&lt;-</span> <span class="fu">resp_styles</span>(NEP_positively_polarized, <span class="dv">1</span>, <span class="dv">5</span>,<span class="at">min_valid_responses =</span> <span class="dv">1</span>,<span class="at">normalize =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s now inspect response style indicators for the positively polarized NEP scale:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize and print results over all respondents</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>NEP_positively_polarized_respstyles_table <span class="ot">&lt;-</span> <span class="fu">summary</span>(NEP_positively_polarized_respstyles)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(NEP_positively_polarized_respstyles_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 3%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">MRS</th>
<th style="text-align: left;">ARS</th>
<th style="text-align: left;">DRS</th>
<th style="text-align: left;">ERS</th>
<th style="text-align: left;">NERS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Min. : 0.000</td>
<td style="text-align: left;">Min. : 0.000</td>
<td style="text-align: left;">Min. : 0.000</td>
<td style="text-align: left;">Min. : 0.000</td>
<td style="text-align: left;">Min. : 0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">1st Qu.: 1.000</td>
<td style="text-align: left;">1st Qu.: 7.000</td>
<td style="text-align: left;">1st Qu.: 3.000</td>
<td style="text-align: left;">1st Qu.: 1.000</td>
<td style="text-align: left;">1st Qu.: 9.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Median : 2.000</td>
<td style="text-align: left;">Median : 8.000</td>
<td style="text-align: left;">Median : 5.000</td>
<td style="text-align: left;">Median : 3.000</td>
<td style="text-align: left;">Median :12.00</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Mean : 2.327</td>
<td style="text-align: left;">Mean : 8.211</td>
<td style="text-align: left;">Mean : 4.462</td>
<td style="text-align: left;">Mean : 3.639</td>
<td style="text-align: left;">Mean :11.36</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">3rd Qu.: 3.000</td>
<td style="text-align: left;">3rd Qu.: 9.000</td>
<td style="text-align: left;">3rd Qu.: 6.000</td>
<td style="text-align: left;">3rd Qu.: 6.000</td>
<td style="text-align: left;">3rd Qu.:14.00</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Max. :14.000</td>
<td style="text-align: left;">Max. :15.000</td>
<td style="text-align: left;">Max. :11.000</td>
<td style="text-align: left;">Max. :15.000</td>
<td style="text-align: left;">Max. :15.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">NA’s :285</td>
<td style="text-align: left;">NA’s :285</td>
<td style="text-align: left;">NA’s :285</td>
<td style="text-align: left;">NA’s :285</td>
<td style="text-align: left;">NA’s :285</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape the data for density and box plots</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>NEP_positively_polarized_respstyles_long <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(NEP_positively_polarized_respstyles, </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">cols =</span> <span class="fu">c</span>(<span class="st">"MRS"</span>, <span class="st">"ARS"</span>, <span class="st">"ERS"</span>), </span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">names_to =</span> <span class="st">"Indicator"</span>, </span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">values_to =</span> <span class="st">"Value"</span>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove NAs (for those we have no calculated indicators)</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>NEP_positively_polarized_respstyles_long <span class="ot">&lt;-</span> NEP_positively_polarized_respstyles_long <span class="sc">%&gt;%</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Value))</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean for each Indicator</span></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>mean_values <span class="ot">&lt;-</span> NEP_positively_polarized_respstyles_long <span class="sc">%&gt;%</span></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Indicator) <span class="sc">%&gt;%</span></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_value =</span> <span class="fu">mean</span>(Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Create combined boxplot and density plot with a dashed line for each mean</span></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(NEP_positively_polarized_respstyles_long, <span class="fu">aes</span>(<span class="at">x =</span> Value, <span class="at">y =</span> <span class="fu">after_stat</span>(scaled))) <span class="sc">+</span></span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(scaled)), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="sc">-</span><span class="fl">0.5</span>), <span class="at">width =</span> <span class="fl">0.5</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightgray"</span>) <span class="sc">+</span></span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">data =</span> mean_values, <span class="fu">aes</span>(<span class="at">xintercept =</span> mean_value, <span class="at">color =</span> <span class="st">"Mean"</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb42-22"><a href="#cb42-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Mean"</span> <span class="ot">=</span> <span class="st">"black"</span>)) <span class="sc">+</span></span>
<span id="cb42-23"><a href="#cb42-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Indicator, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb42-24"><a href="#cb42-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Combined Density and Box Plots of Indicators with Mean Values"</span>,</span>
<span id="cb42-25"><a href="#cb42-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Value"</span>,</span>
<span id="cb42-26"><a href="#cb42-26" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Scaled Density / Boxplot"</span>) <span class="sc">+</span></span>
<span id="cb42-27"><a href="#cb42-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb42-28"><a href="#cb42-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"right"</span>,</span>
<span id="cb42-29"><a href="#cb42-29" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.title =</span> <span class="fu">element_blank</span>())  <span class="co"># Remove legend title</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Resquin_Tutorial_v2_files/figure-html/summary%20statistics%20NEP%20resp_styles-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The distribution of response style indicators across all respondents of the NEP-scale, reveals the following patterns:</p>
<ul>
<li><p><strong>MRS:</strong> Respondents on average select the middle response for three out of the 15 items of the NEP scale. Respondents with more than nine mid-point responses are outliers in the sample while respondents maximally selected 11 mid-point responses for the 15 items. Similarly to the institutional trust scale, this distribution pattern suggest that mid-point responding is not a dominant response style for the NEP scale among our sample. Therefore, outliers should be carefully checked regarding their response behavior to exclude data quality issues.</p></li>
<li><p><strong>ARS:</strong> On average, respondents show a remarkable high amount of agreeing responses by agreeing with about 11 out of 15 items. This suggests that the data of the NEP scale might be affected by agreement bias that does not reflect respondents true values. Especially against the background of reversely coded items (i.e., eight items are formulated pro-environmental and 7 items are formulated anti-environmental) this amount of average agreement contradicts reported attitudes. This concern of data quality is further undermined by respondents on maximum agreeing with all of the items of the scale irrespective of their opposite wording. Therefore, respondents with more than eight agreeing responses across items should be flagged, closely checked regarding their response behavior, and additional proxies, such as their response times, should be investigated to gain further insights into the quality of their responses.</p></li>
<li><p><strong>ERS:</strong> On average, respondents select the extreme end-points of the scale to about two to three out of 15 items. Respondents with more than 8 extreme responses across the items of the scale are considered outliers in the sample. Overall, the distribution suggests that respondents indeed avoid extreme answers and stick to more moderate positions. Consequently, those with a high amount of given extreme responses and respondents who provided endpoint responses to all of the 15 items of the scale should be carefully investigated regarding any data quality concerns.</p></li>
</ul>
<p><em>In summary</em>, the distribution of response style indicators for the NEP-scale suggests that the measure is generally not affected by mid-point or extreme responding although some outliers give cause for data quality concerns and should be flagged for further investigation. Nevertheless, the data of the NEP-scale seems to be remarkably affected by agreement bias with the average respondent providing agreeing responses to 10 out of 15 items despite their reverse wording. Respondents with more agreeing responses than positively or negatively formulated items should be flagged and closely inspected regarding the quality of their responses. This in particular true for those respondents who straightlined across the items of the scale.</p>
<!--Info box -->
<p><strong>Good to know</strong> Although <code>resquin</code> and <code>resp_styles</code> is typically designed for multi-item scales or matrix questions that share the same question introduction and response scale, it is also possible to evaluate “stand-alone” survey questions (e.g., attitudes toward governmental spending, attitudes toward social policies) from a broader topic (e.g., political attitudes) together. If you want to do so, it is crucial to only investigate those “stand-alone” questions together which have the same number of response options. Also, you want to make sure that the questions are not separated from each other in the questionnaire but are in a consecutive order. As long as the several questions are sequential and share the same response scale, it is possible to calculate meaningful indicators of response styles.</p>
</section>
</section>
</section>
<section id="conclusion-and-recommendations" class="level1">
<h1>Conclusion and recommendations</h1>
<p><em>Institutional Trust Scale</em> Overall, responses of the institutional trust scale are not affected by any major response bias. However, we do find unusual response patterns regarding straightlining responses and outliers in the sample who showed an unusual extent of mid-point and extreme responding. These respondents should definitely be flagged and ideally, their response behavior should be investigated in greater detail.</p>
<p><em>NEP Scale</em> Similarly, responses of the NEP scale are not affected by mid-point or extreme responding, although again, outliers give reason for data quality concerns. Additionally, we find straightlining response behavior with on overall, a low prevalence of only 0.5% of straightlining responses. However, these respondents most likely present a data quality concern due to the reversely coded nature of the scale. Most importantly, the data is affected by acquiescence bias with respondents on average agreeing to 10 out of 15 items. Again, due to the reversely coded items of the scale, this pattern suggests poor data quality with responses detached from true values. Respondents with suspicious response behaviors should be flagged and ideally further checked.</p>
<p><strong>Straightlining:</strong> Straightlining response behavior is generally seen as a sign of low engagement and of respondents providing only minimal effort in the response generation process, which can potentially compromise data quality. However, we advise against interpreting straightlining behavior blindly as a data quality issue. Dependent on the underlying response scale and the construct to be measured, straightlining can sometimes reflect valid and genuine responses. One useful criterion to assess whether straightlining can be valid or reflects poor quality responses is to determine whether the underlying scale contains reversely coded items. In our example, we cannot fully exclude the possibility that straightlining response behavior in the institutional trust scale indicates genuine trust or distrust across all listed institutions or a respondents’ genuine indifference, especially in the case of the absence of a “don’t know” - response option. For the NEP-scale on the other hand, straightlined responses across item contradict each other as half of the items measure pro-environmental and the other half anti-environmental attitudes. Therefore, we recommend to always pay attention to the construct measured and how the scale measures it to assess whether all straightlining respondents are a severe threat to data quality.</p>
<p><strong>Acquiescence response style:</strong> Acquiescence bias is again considered a sign of respondents’ low engagement with a question that results in poor quality responses. In multi-item scales, acquiescence bias is somewhat tricky to determine. Similarly to straightlining response behavior, high shares of agreeing responses across items does not necessarily reflect response bias. Scales measuring widely accepted values for instance, can show high agreement among respondents without reflecting an acquiescence bias that indicates poor response quality. However, again the underlying scale can provide information on the severeness of an acquiescence response pattern across items. In the case of the NEP-scale with conflicting statements/items, a high share of agreeing responses give reason for concern and most likely represent biased responses. In general, we advise to take acquiescence response styles seriously and to assess their implications for the responses of a multi-item scale based on the content and formulation of items.</p>
<p><strong>Outliers:</strong> We recommend to deal with outliers in the sample regarding both response distribution and response style indicators similarly to dealing with any outlier in a response distribution. First, you should attempt to understand the outlying observations and closely inspect the response behavior of these respondents. In any case, we advise against dropping these observations from the sample and instead, to flag these respondents for your further analyses.</p>
<p><strong>Recommendation:</strong> Knowing how to assess and interpret indicators of response distribution and response styles regarding response quality, you probably wonder how to move on from there?</p>
<ul>
<li><p>Ideally, we recommend to conduct further analyses on respondents with suspicious response patterns. A typical proxy to understand the response generation process underlying a response pattern and to understand whether responses represent a data quality issue are <em>response times</em>. If respondents show extremely short response times for a question, you can assume that respondents provided no to minimal effort to process the question which consequently resulted in poor quality responses. A common threshold to assess whether response times are too short to process a question is introduced by <span class="citation" data-cites="zhang2014speeding">Zhang and Conrad (<a href="#ref-zhang2014speeding" role="doc-biblioref">2014</a>)</span>.</p>
<p>Further measures to approach the question whether respondents’ answers reflect low engagement with a question and therefore, poor quality responses are <em>respondent motivation</em> or <em>respondent cognitive ability</em>. These are both factors discussed to influence the occurrence and magnitude of <em>satisficing</em>, an umbrella term for different response strategies that can be used as shortcuts to reduce cognitive burden and can therefore, reflect careless responding (<span class="citation" data-cites="krosnick1991response">Krosnick (<a href="#ref-krosnick1991response" role="doc-biblioref">1991</a>)</span>).</p></li>
<li><p>For your further analyses, we recommend in any case to not simply drop respondents with suspicious response patterns. Instead, we advise to always flag them and run sensitivity analyses both including and excluding the respective respondents to gain insights on whether their responses affect your overall findings.</p></li>
</ul>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<section id="how-to-cite-this-work" class="level3">
<h3 class="anchored" data-anchor-id="how-to-cite-this-work">How to Cite This Work</h3>
<p>Kraemer, Fabienne, Arjin Eser, and Çağla Yıldız (2024) <em>Assessing Response Quality and Careless Responding in Multi-Item Scales</em>. KODAQS Data Quality Toolbox.</p>

</section>
</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-dunlap_et_al_2002" class="csl-entry" role="listitem">
Dunlap, Riley E., Kent D. Van Liere, Angela G. Mertig, and Robert Emmet Jones. 2002. <span>“New Trends in Measuring Environmental Attitudes: Measuring Endorsement of the New Ecological Paradigm: A Revised NEP Scale.”</span> <em>Journal of Social Issues</em> 56 (3): 425–42. <a href="https://doi.org/10.1111/0022-4537.00176">https://doi.org/10.1111/0022-4537.00176</a>.
</div>
<div id="ref-ZA5666" class="csl-entry" role="listitem">
GESIS Panel, Team. 2017. <span>“GESIS Panel - Campus File.”</span> GESIS Data Archive, Cologne. ZA5666 Data file Version 1.0.0. <a href="https://doi.org/10.4232/1.12749">https://doi.org/10.4232/1.12749</a>.
</div>
<div id="ref-kim_et_al_2019" class="csl-entry" role="listitem">
Kim, Yujin, Jennifer Dykema, John Stevenson, Peter Black, and Daniel P. Moberg. 2019. <span>“Straightlining: Overview of Measurement, Comparison of Indicators, and Effects in Mail–Web Mixed-Mode Surveys.”</span> <em>Social Science Computer Review</em> 37 (2): 214–33. <a href="https://doi.org/10.1177/0894439317752406">https://doi.org/10.1177/0894439317752406</a>.
</div>
<div id="ref-krosnick1991response" class="csl-entry" role="listitem">
Krosnick, J. A. 1991. <span>“Response Strategies for Coping with the Cognitive Demands of Attitude Measures in Surveys.”</span> <em>Applied Cognitive Psychology</em> 5 (3): 213–36. <a href="https://doi.org/10.1002/acp.2350050305">https://doi.org/10.1002/acp.2350050305</a>.
</div>
<div id="ref-zhang2014speeding" class="csl-entry" role="listitem">
Zhang, C., and F. Conrad. 2014. <span>“Speeding in Web Surveys: The Tendency to Answer Very Fast and Its Association with Straightlining.”</span> <em>Survey Research Methods</em> 8: 127–35. <a href="https://doi.org/10.18148/srm/2014.v8i2.5453">https://doi.org/10.18148/srm/2014.v8i2.5453</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>